[[questions]]
question     = "What is the square root of 81'"
answer       = "9"
alternatives = ["162", "3", "27"]

[[questions]]
question     = "What is the probability of getting two heads when you flip a fair sided coin twice"
answer       = "1/4"
alternatives = ["1/2", "2/8", "1/8"]

[[questions]]
question = "What is the square of 15"
answer = "225"
alternatives=["5", "30", "150",]
    

[[questions]]
question     = "what is the cube root of 27"
answer       = "3"
alternatives = ["27", "9", "3,9"]

[[questions]]
question = "What is the correct name for this sign √ "
answer = "Radical Sign"
alternatives = [
    "Surd Sign",
    "square root",
    "cube root",
]

[[questions]]
question     = "What is 7^3"
answer       = "343"
alternatives = ["49", "7", "323"]

[[questions]]
question = "Tickets numbered 1 to 20 are mixed up and then a ticket is drawn at random. What is the probability that the ticket drawn has a number which is a multiple of 3 or 5? "
answer = "9/20"
alternatives = [
    "1/2",
    "3/4",
    "13/20.",
]

[[questions]]
question = "What is the probability of getting a sum 9 from two throws of a dice?"
answer = "1/3"
alternatives = [
    "1/2",
    "2/3",
    "2/6",
]

[[questions]]
question = "A bag contains 2 red, 3 green and 2 blue balls. Two balls are drawn at random. What is the probability that none of the balls drawn is blue?"
answer = "10/21"
alternatives = [
    "11/21",
    "5/7",
    "2/7",
]

[[questions]]
question = "what is the final value of this expression (2 √4 * 3 √9) ?"
answer = "36"
alternatives = [
    "35",
    "154",
    "28",
]